# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: orvice/ss-panel:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u "$USER" -p "$PASSWD"  
    - docker build --pull -t "orvice/ss-panel:latest" .
    - docker push "orvice/ss-panel:latest"
